[build-system]
requires = ["hatchling>=1.22.0"]
build-backend = "hatchling.build"

[project]
name = "scriptkiddie-core"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["pyyaml>=6.0.1", "pathspec>=0.12.1", "pydantic>=2.7.4"]

[project.optional-dependencies]
dev = ["pytest>=8.0", "pytest-cov>=5.0"]

[tool.hatch.build.targets.wheel]
packages = ["src/scriptkiddie_core"]

[tool.pytest.ini_options]
testpaths = ["tests"]
