[build-system]
requires = ["hatchling>=1.22.0"]
build-backend = "hatchling.build"

[project]
name = "scriptkiddie-core"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["pyyaml>=6.0.1", "pathspec>=0.12.1", "pydantic>=2.7.4"]

[tool.hatch.build.targets.wheel]
packages = ["src/scriptkiddie_core"]
